nickmerwin/node-coveralls

README.md
Let me know if you think this makes it more clear.
=> Update README to be more clear

README.md
It should be http://mochajs.org/
=> Fix mocha's link

lib/convertLcovToCoveralls.js, lib/getOptions.js
setting the github pull request plugin's environment variables with the option coveralls is expecting
=> Added support for service_pull_request in jenkins

lib/getOptions.js, test/convertLcovToCoveralls.js, test/getOptions.js
See https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
=> Get PR number from TRAVIS

package.json
- Update request, nyc, istanbul, mocha to the latest version
- Ref nickmerwin/node-coveralls#149
=> Update outdated dependencies

.travis.yml, package.json
Fixes #171
Fixes #170
Fixes #153
Fixes #149
Fixes #133
=> Expand allowed dependency versions to all API compatible versions

lib/getOptions.js, package-lock.json, test/getOptions.js
Semaphore ENV variables: https://semaphoreci.com/docs/available-environment-variables.html
=> Add Semaphore support

README.md, lib/getOptions.js, test/getOptions.js
- Adds support for reporting from Buildkite build agents - Documentation for environment variables is available here: https://buildkite.com/docs/builds/environment-variables
=> Add buildkite support

.snyk, .travis.yml, package-lock.json, package.json
=> dependency security audit fixes from npm & snyk

lib/handleInput.js
Sorry, I was checking out the code and this really bothered me lol
=> Style fix on input handler

lib/getOptions.js, test/getOptions.js
Added the necessary mapping from environment variables set by Azure Pipelines to the relevant properties in this lib.
Addresses #213
=> Add support for Azure Pipelines

lib/getOptions.js
With [Jenkins Blue Ocean](https://jenkins.io/projects/blueocean/), there are new environment variables to use such as `CHANGE_*`.
=> Update configuration logic for Jenkins

package-lock.json, package.json
js-yaml and 3 others.
- https://github.com/nodeca/js-yaml/issues/475
- https://github.com/nodeca/js-yaml/pull/480
=> fix: vulnerabilities

lib/logger.js
Sorry about this @nickmerwin :/
=> Fix logger regression.

.github/workflows/test.yml
https://github.com/actions/setup-node/issues/27
=> CI: work around actions/setup-node issue.

lib/getOptions.js, test/getOptions.js
This PR adds [Codefresh](https://codefresh.io/) support based on the [docs](https://codefresh.io/docs/docs/codefresh-yaml/variables/).
=> Add Codefresh support

lib/getOptions.js, test/getOptions.js
- Set service_name and/or repo_token from .coveralls.yml regardless of if $COVERALLS_REPO_TOKEN is set
- Fixes #273, #161
=> Set service_name and/or repo_token from .coveralls.yml regardless of if $COVERALLS_REPO_TOKEN is set

README.md
Addresses only the `jest` case, other cases can be handled via
subsequent pull requests.
=> Only coverage report on test success, fixes #230

.github/workflows/test.yml
Creating a PR to test Coveralls behavior.
=> GH Action workflow update

package-lock.json, package.json, test/handleInput.js, test/sendToCoveralls.js
Closes #268, fixes #261
@nickmerwin this is #268 cherry picked and rebased to fix any conflicts.
I'm not familiar with sinon's API but tests do seem to pass.
=> Update sinon to v7.5.0.

lib/convertLcovToCoveralls.js, lib/getOptions.js, test/convertLcovToCoveralls.js, test/getOptions.js
This implements the ideas in https://github.com/nickmerwin/node-coveralls/pull/205
And should fix https://github.com/nickmerwin/node-coveralls/issues/134
=> Handle service_job_number for parallelism in Travis and CircleCI

package-lock.json, package.json
@nickmerwin if this needs a rebase later, please ping me :)
=> package.json reorder properties and update package-lock.json
