- lib/fetchGitData.js
Given the commit message
tree 2d257d54add0901a72fbe492538aec4a35b4f4a5
parent 21d9ce4eb278af46561e069d6410e72a88c38036
author Joshua Ma <josh@benchling.com> 1436838814 -0700
committer Joshua Ma <josh@benchling.com> 1436839048 -0700
main message
secondary detail
REGEX_COMMIT_DETAILS previously incorrectly matched `secondary detail` as the
message - it lets an optional newline match (A), followed by nongreedy
`[\S\s]+`, until a double-newline (B) is found. The message used is what
follows B. Since there's two double-newlines, before `main message` and
`secondary detail`, the first double-newline is used towards (A) and the second
set is the one that matches (B). So the message ends up being `secondary
detail`.
This change simplifies the regex to just a nongreedy `[\S\s]*` until the first …
> Fix parsing git message with REGEX_COMMIT_DETAILS

- lib/convertLcovToCoveralls.js
- lib/getOptions.js
- test/convertLcovToCoveralls.js
- test/getOptions.js
Resolves: https://github.com/nickmerwin/node-coveralls/issues/100.
The [ruby gem implementation](https://github.com/lemurheavy/coveralls-ruby/blob/master/lib/coveralls/configuration.rb#L50) includes this for a bunch of CI servers.  Not sure if it's required for commenting on pull requests but either way is a nice to have.
> Pass CI_PULL_REQUEST through to coveralls if it is set

- README.md
I took a quick stab at adding the command line params to the README.
Related to an issue I opened: https://github.com/cainus/node-coveralls/issues/73
> Add command line params to README

- lib/sendToCoveralls.js
- test/sendToCoveralls.js
To allow using this tool with Coveralls Enterprise, I've added support in `sendToCoveralls` to read the host from a `COVERALLS_ENDPOINT` environment variable (if it exists), else default to coveralls.io (as before).
> Added support for process.env.COVERALLS_ENDPOINT

- lib/getOptions.js
- lib/handleInput.js
- test/getOptions.js
I'm using this library in a grunt task to pipe merged lcov results to coveralls. However, the karma-coverage tool outputs relative paths in its lcov output, and because this library grabs its basepath from argv, it doesn't work out of the box.
For instance, calling
```js
grunt lcovMerge
```
produces a base path at ~/dev/my/repo/lcovMerge. My current workaround is to explicitly set argv:
```js
var oldArgv = process.argv[2];
process.argv[2] = '';
require('coveralls').handleInput(lcov, function(err) {
process.argv[2] = oldArgv;
if (err) {
return done(err);
}
done();
});
```
This change would let me pass in the basepath I'd like, and make using this as a library more easy in general.
I maintained backcompat in this commit, at the expense of an odd ordering of parameters - let me know if you'd …
> allow users to pass options through.

- package.json
coveralls@^2.6.1 resolves to coveralls@2.11.4, depends on request@2.40.0 - https://github.com/nickmerwin/node-coveralls/blob/master/package.json#L35
request@2.40.0 depends on form-data@~0.1.0 - https://github.com/request/request/blob/v2.40.0/package.json#L33 (so does 3.0, watch out)
form-data@~0.1.0 resolves to @0.1.4, depends on async0.9.2 - https://github.com/form-data/form-data/blob/0.1.4/package.json#L20
async0.9.2 depends on deprecated lodash@2.4.1 - https://github.com/caolan/async/blob/0.9.2/package.json#L28
coveralls@master also depends on request@2.40.0 and should be updated to - https://github.com/request/request/blob/v2.67.0/package.json#L29
> Resolve Lodash deprecation warning

- lib/fetchGitData.js
Instead of matching the git commit file for emails which contain
at least one character, match for “emails” which also may be empty.
Also, use greedy regex matching in those places which is likely
to be more performant than non-greedy matching.
(#86)
> Fix bug #86

- README.md
Added documentation for `nyc`, a general purpose code-coverage tool which works with all testing frameworks, and for `node-tap` which now uses `nyc` to generate coverage reports.
CC: @isaacs.
> added documentation for nyc and node-tap

- lib/detectLocalGit.js
According to git-check-ref-format(1), branch naming excludes a number of characters, but various non-word characters are definitely allowed.
This modifies the `REGEX_BRANCH` detection to match branch names containing some non-word characters, e.g. `features/foo` or `bar-baz`.
> Accept more valid git branch names

- lib/convertLcovToCoveralls.js
- lib/getOptions.js
- test/getOptions.js
This adds support for node-coveralls to post the service_pull_request for CircleCI.
- Unfortunately they don't have an environment variable that is the PR number itself, so there is minor string manipulation to get it working.
> Add support for CircleCI commenting on PRs

- .travis.yml
- index.js
- lib/getOptions.js
- lib/logger.js
- lib/sendToCoveralls.js
- package.json
- test/getOptions.js
- test/logger.js
- test/sendToCoveralls.js
Adds the command line option pair -w/--write.
These options indicate that the output should be written to standard output,
rather than being posted to coveralls.io, which may be useful for debugging,
mixed-language codebases (e.g. node addons with C++ code) etc.
This includes a test case. In some places, the code was changed to allow a
variable number of command line options (which I would consider useful in
general).
> Add command line option to write output to stdout

- package.json
There's a remote memory exposure vulnerability in the current version of `request`. This bumps that version to the latest current as well as bumping the core packages patch version.
Details here:
https://snyk.io/vuln/npm:request:20160119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nickmerwin/node-coveralls/125)
> Bump "request" NPM module to fix security issue

- package.json
Fixes upstream `tough-cookie` ReDOS https://nodesecurity.io/advisories/130
> Update `request` to v2.74.0

- lib/getOptions.js
- test/getOptions.js
Hi @nickmerwin 
Codeship has published its new Docker implementation with some helpful environment variables. I think many people who're using docker will be glad to remove the .git files from the container.
[https://codeship.com/documentation/docker/steps/#build-environment](Codeship Docker configuration)
Marc
> Feature: Support codeship docker environment variables

- lib/getOptions.js
- test/getOptions.js
This PR adds support for [Surf](https://github.com/surf-build/surf), which is a toolkit for making your own CI server for GitHub.
> Add Surf support

- .snyk
- .travis.yml
- README.md
- package.json
- test/fetchGitData.js
- test/getOptions.js
Add `snyk` for vulnerability checking.
Update all dependencies to the latest versions to resolve identified vulnerabilities.
Update tests broken by the dependency update of `should`.
Update CI to include all long-term support and major releases of node, and iojs.
> Update CI, vulnerability checking, and dependencies.

- lib/convertLcovToCoveralls.js
- test/convertLcovToCoveralls.js
A project I am working (specifically and Ember application that has several ember addons) on is writing erroneous file paths to it's `lcov.dat` file. 
This fix would cause graceful failure.
I did not add logging, but I can do that if if you feel it's necessary.
> Ignore files that do not exist in convertLcovToCoveralls

- package.json
This update seems to have been reverted during a merge.
> Update `request` to 2.75.0

- lib/getOptions.js
- test/getOptions.js
With Drone dropping the hosted service (https://archive.drone.io) and going open source (https://github.com/drone/drone), I wanted to give it and Coveralls a shot. 
My initial setup consisted of setting the COVERALLS_REPO_TOKEN env variable and running `nyc` on top of my `mocha` tests as part of my builds on a self-hosted Drone CI. 
```sh
export COVERALLS_REPO_TOKEN=...
nyc mocha && nyc report | coveralls
```
This worked just dandy™ - but there wasn't enough data being sent through the `coveralls` script to coveralls.io to get the status API / automated comments going. 
--- 
This PR re-enables Drone as a CI environment and supplies some more of the available Drone environment data (http://readme.drone.io/0.5/usage/environment-reference/).
* Drone build number
* PR number
* Commit author …
> Reenabling Drone

- .travis.yml
It's making run the CI with older versions of Node releases and more importantly with branches that don't receive security patches.
I also think it will make the CI for https://github.com/nickmerwin/node-coveralls/pull/152 pass.
> don't hardcode minor version

- .gitignore
- lib/detectLocalGit.js
- package.json
- test/detectLocalGit.js
In circle-ci I was getting failures due to their git clone process not providing a reference in `.git/refs/heads/master`. If that is not available, get the commit hash from `.git/packed-refs`.
> Parse commit from packed refs if not available in refs dir.

- README.md
I found https://github.com/nickmerwin/node-coveralls/pull/124. It looks like AppVeyor support is in place, but it's not mentioned in the README.
> Add mention about AppVeyor to the README

- README.md
Also included link to my project where I am successfully implementing jest coverage and travis-ci
> Update examples to include Jest

- test/getOptions.js
`fs.exists` doesn't return anything and calling it without a callback is useless.
Probably `fs.existsSync` was meant to be called here.
_Note: this was found using a semi-automated ecosystem scan.
I have not tested this change, but looks like an obvious mistype. Placing hopes in CI._
I suggest to additionaly inspect that codepath, because probably some tests/usecases were broken.
Refs: nodejs/node#18668
> Fix a mistype in tests: fs.exists -> fs.existsSync

- test/getOptions.js
- done callback waits for unlink in testRepoTokenDetection to prevent race condition
Previously this would sometimes result in the file referenced by `fs` existing when the next test was executed, resulting in the configuration file's properties being inherited by the next test erroneously.
> Prevent testRepoTokenDetection race condition

- lib/logger.js
- lib/sendToCoveralls.js
I'm attempting to get node-coveralls running inside docker on travis and I'm running into some problems. In trying to figure out what is wrong I discovered that verbose mode simply isn't verbose. Verbose mode currently sets the debug level to `warn` and this PR changes it to debug.
> Almost no info available via verbose mode `-v` - change log level to debug

- package-lock.json
- package.json
If this is accepted, I could look into replacing `istanbul` with `nyc` and moving to `npm scripts`.
BTW the engines version says Node.js 4.0.0, but Node.js >= 6 are tested on CI.
Closes #191, closes #200, closes #215, closes #228
> Update dependencies except for should.

- test/convertLcovToCoveralls.js
- test/detectLocalGit.js
- test/handleInput.js
```
C:\Users\xmr\Desktop\node-coveralls>npm run mocha
> coveralls@3.0.6 mocha C:\Users\xmr\Desktop\node-coveralls
> _mocha -b -R spec
convertLcovToCoveralls
√ should convert a simple lcov file
√ should pass on all appropriate parameters from the environment
√ should work with a relative path as well
√ should convert absolute input paths to relative
√ should handle branch coverage data
√ should ignore files that do not exists
√ should parse file paths concatenated by typescript and ng 2
detectLocalGit
√ should get commit hash from packed-refs when refs/heads/master does not exist
fetchGitData
√ should throw an error when no data is passed
√ should throw an error when no git context is provided
√ should throw an error if no head is provided
√ should throw an error if no head.id is provided …
```
> Fix tests on Windows.

- package-lock.json
- package.json
This will conflict with #234 but I can rebase either one when needed.
> Remove the unused growl dependency.

- lib/convertLcovToCoveralls.js
- package-lock.json
- package.json
This adds support for files that can be produced by pytest and coverage.py and many other job runners.
if this gets merged ill have a small PR for the github action to use this new setting
> add ability to parse cobertura files

- .github/workflows/test.yml
Fixes #258 
This isn't perfect, but with the current state it works fine. It will fail if one changes `8` to `8.0.0`. I could make it work in this case too, but since we don't use it currently I went with the easiest approach.
> CI: use `npm ci` on Node.js >=8.

- .snyk
- README.md
- package-lock.json
- package.json
After #234 and #235 and assuming automated security fixes are enabled, snyk isn't needed IMO. We'll be down to zero vulnerabilities and if any new ones come up, dependabot will provide any patches, assuming they exist.
This gets rids of [a lot](https://packagephobia.now.sh/result?p=snyk) of devDependencies and does not require one to login to be able to do `npm test` locally.
IMO it's a win-win situation, as long as automated security fixes are set up.
Fixes #245
> Remove snyk.

- lib/convertLcovToCoveralls.js
- package-lock.json
- package.json
cobertura-parse is archived and in bad shape. They even have mocha in dependencies.
See also [my comment](https://github.com/nickmerwin/node-coveralls/pull/243#issuecomment-556948457)
> Remove cobertura-parse (reverts #243)

- package-lock.json
- package.json
The current version 1.2.0 has some security issues [please refer](https://app.snyk.io/vuln/SNYK-JS-MINIMIST-559764).
> #278 Upgrades minimist dependency to 1.2.5

- lib/convertLcovToCoveralls.js
The check is already done above.
https://github.com/nickmerwin/node-coveralls/blob/eaba7c60d3936ea0d73490486c36ed347149e8c0/lib/convertLcovToCoveralls.js#L67-L69
> remove redundant code

- .github/workflows/test.yml
* add Node.js 14
* rename job to test
* uppercase `GITHUB_TOKEN` for consistency
* remove no longer needed steps; `actions-setup-node` prints this by default now
@nickmerwin: We could/should probably not run lint on all Node.js versions since it's moot, but that's for another time 🙂
> Minor CI tweaks

- package.json
This will prevent tests not checking for errors.
> xo: make `handle-callback-err` an error.
